spring.application.name=PruebaBack
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
application.security.jwt.secret-key=TXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25XaGljaElzMzJCeXRlc0xvbmc=
application.security.jwt.expiration=86400000